spring.application.name=JPOSServer
server.port=8000
spring.datasource.url=jdbc:postgresql://localhost:5432/jpos_practice
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
